---
title: "Data Science Portfolio  |  Michael Jahn, PhD"
output:
  html_document:
    theme: cosmo
    df_print: paged
  html_notebook:
    theme: cosmo
  pdf_document: default
---

----------

```{r, echo = FALSE}
# GLOBAL OPTIONS
# ==============
#
# attach libraries
suppressPackageStartupMessages({
  library(tidyverse)
  library(scholar)
  library(gh)
  library(waffle)
})

# ggplot theme and palette
theme_portfolio <- theme_minimal(base_size = 10) +
  theme(
    panel.grid.minor = element_blank(),
    panel.grid.major = element_line(color = grey(0.8), linewidth = 0.35),
    axis.title = element_blank(),
    plot.title = element_text(face = "bold", size = 10)
  )

portfolio_cols <- c("#1B9E77", "#D95F02", "#7570B3", "#E7298A", "#66A61E", "#E6AB02", "#A6761D", "#666666")

# set scholar ID
scholar_id <- "jApo8PEAAAAJ"

# set github user ID
github_id <- "m-jahn"
github_token <- Sys.getenv("GITHUB_TOKEN")

# options
top_pubs <- 6
top_proj <- 6
```

## Summary

- 15 years of experience in life science and data science
- published `r get_num_articles(scholar_id)` articles in `r get_num_distinct_journals(scholar_id)` peer-reviewed journals
- supervised master students, graduate students and junior postdocs
- build and maintain open source pipelines and software packages (snakemake, python, R)
- passionate about open science, transparency and reproducibility

----------

## Publications

```{r, echo = FALSE}
# retrieve publication stats
df_pubs <- get_publications(scholar_id)
```


```{r, echo = FALSE, fig.width = 10, fig.height = 2.5}
# plot cumulative number of publications over time
df_sum_pubs <- df_pubs %>%
  filter(!is.na(year)) %>%
  group_by(year) %>%
  summarize(num_of_pubs = n()) %>%
  # add missing years
  complete(year = min(year):max(year)) %>%
  mutate(num_of_pubs = replace_na(num_of_pubs, 0)) %>%
  # calculate cumulative sum
  mutate(cum_sum_of_pubs = cumsum(num_of_pubs))

plot_sum_pubs <- ggplot(df_sum_pubs, aes(x = year, y = cum_sum_of_pubs)) +
  geom_line(linewidth = 1, color = portfolio_cols[1]) +
  geom_point(size = 2, color = portfolio_cols[1]) +
  labs(title = "Cumulative number of publications") +
  theme_portfolio

# plot top X citations
df_top_pubs <- df_pubs %>%
  slice(1:top_pubs) %>%
  mutate(abbr = author %>% str_split_i(", ", 1) %>% str_split_i(" ", 2) %>%
    unname() %>% paste0(" et al., ", journal, ", ", year)) %>%
  mutate(rank = row_number()) %>%
  mutate(rank_f = forcats::fct_rev(factor(rank)))

plot_top_pubs <- ggplot(df_top_pubs, aes(x = cites, y = rank_f, color = factor(rank))) +
  geom_segment(aes(x = 0, xend = cites, yend = rank_f), linewidth = 1.1) +
  geom_point(size = 2.2) +
  geom_text(aes(x = 0, label = abbr), hjust = -0.04, vjust = 1.5, size = 2.6, show.legend = FALSE) +
  coord_cartesian(xlim = c(max(df_pubs$cites) * -0.08, max(df_pubs$cites) * 1.08), clip = "off") +
  scale_color_manual(values = portfolio_cols[seq_len(top_pubs)]) +
  labs(title = paste("Top", top_pubs, "publications by citation")) +
  theme_portfolio +
  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank(), legend.position = "none")

grid::grid.newpage()
print(plot_top_pubs, vp = grid::viewport(x = 0.25, y = 0.5, width = 0.5, height = 1))
print(plot_sum_pubs, vp = grid::viewport(x = 0.75, y = 0.5, width = 0.5, height = 1))
```

----------

## Citations

```{r, echo = FALSE, fig.width = 10, fig.height = 2.5}
# retrieve citation stats
df_cites <- get_citation_history(scholar_id) %>%
  mutate(`cites cumulative` = cumsum(cites))

# plot citations over time
plot_cites <- ggplot(df_cites, aes(x = year, y = cites)) +
  geom_col(fill = portfolio_cols[2], width = 0.8) +
  labs(title = "Citations per year") +
  theme_portfolio

plot_cites_cum <- ggplot(df_cites, aes(x = year, y = `cites cumulative`)) +
  geom_col(fill = "#66A61E", width = 0.8) +
  labs(title = "Cumulative citations per year") +
  theme_portfolio

# arrange plots next to each other
grid::grid.newpage()
print(plot_cites, vp = grid::viewport(x = 0.25, y = 0.5, width = 0.5, height = 1))
print(plot_cites_cum, vp = grid::viewport(x = 0.75, y = 0.5, width = 0.5, height = 1))
```

----------

## Projects & Packages

```{r, echo = FALSE, warning=FALSE, message=FALSE}
# use the 'gh' R package to pull user/project information from github;
# use extra options to increase number of fetched events
# per_page - Results per page (default: 30, max: 100)
# page - Page number of the results to fetch, default: 1
gh_repos <- gh("GET /users/{username}/repos", username = github_id, .token = github_token, .limit = 100)
gh_events <- gh("GET /users/{username}/events", username = github_id, .token = github_token, .limit = 100)

df_gh_repos <- lapply(gh_repos, FUN = function(x) {
  unlist(x[c(
    "id", "name", "full_name", "html_url", "fork", "size",
    "stargazers_count", "watchers_count", "has_issues"
  )], recursive = FALSE)
}) %>%
  set_names(., lapply(., function(x) x[["name"]])) %>%
  as.data.frame() %>%
  t() %>%
  as_tibble() %>%
  type_convert(col_types = cols()) %>%
  arrange(desc(stargazers_count))

df_gh_events <- lapply(gh_events, FUN = function(x) {
  unlist(x[c("id", "type", "created_at", "public", "repo")], recursive = TRUE)
}) %>%
  as.data.frame() %>%
  t() %>%
  as_tibble() %>%
  type_convert(col_types = cols()) %>%
  mutate(
    type = str_remove(type, "Event"),
    created_at = as.Date(created_at),
    day = weekdays(created_at, abbreviate = TRUE),
    week = format(created_at, "%W")
  )

weekdays <- c("Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat")
```


```{r, echo = FALSE}
# plot top N popular projects by stars
df_top_proj <- df_gh_repos %>%
  filter(!fork) %>%
  slice(1:top_proj) %>%
  mutate(rank = row_number()) %>%
  mutate(rank_f = forcats::fct_rev(factor(rank)))

plot_top_proj <- ggplot(df_top_proj, aes(x = stargazers_count, y = rank_f, color = factor(rank))) +
  geom_segment(aes(x = 0, xend = stargazers_count, yend = rank_f), linewidth = 1.1) +
  geom_point(size = 2.2) +
  geom_text(aes(x = 0, label = name), hjust = -0.04, vjust = 1.5, size = 2.7, show.legend = FALSE) +
  coord_cartesian(xlim = max(df_top_proj[["stargazers_count"]]) * c(-0.08, 1.08), clip = "off") +
  scale_color_manual(values = portfolio_cols[seq_len(top_proj)]) +
  labs(title = paste("Top", top_proj, "GitHub repos by stars")) +
  theme_portfolio +
  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank(), legend.position = "none")
```


```{r, echo = FALSE}
# plot time series of GH activity
plot_commits_boxes <- df_gh_events %>%
  filter(created_at >= Sys.Date() - 30) %>%
  mutate(type = replace(type, type == "IssueComment", "Issues")) %>%
  mutate(type = replace(type, !type %in% c("Issues", "PullRequest", "Push"), "Other")) %>%
  mutate(week = factor(week, seq(min(week), max(week)))) %>%
  group_by(week, type) %>%
  summarize(commits = n(), .groups = "drop") %>%
  mutate(type = factor(type, levels = c("Push", "PullRequest", "Issues", "Other"))) %>%
  arrange(type) %>%
  ggplot(aes(values = commits, fill = type)) +
  geom_waffle(color = "white", size = 1.125, n_rows = 6) +
  facet_grid(~ week, switch = "x") +
  scale_fill_manual(values = portfolio_cols[c(4,3,1,2)]) +
  labs(title = "Commit activity of past 4 weeks") +
  theme_portfolio +
  theme(axis.text = element_blank(), axis.ticks = element_blank())
```


```{r, echo = FALSE}
# alternative to last plot is tileplot/levelplot, week vs day as on github
# plot time series of GH activity
plot_commits_tiles <- df_gh_events %>%
  filter(created_at >= Sys.Date() - 30) %>%
  group_by(created_at, day, week) %>%
  summarize(commits = n(), .groups = "drop") %>%
  ungroup() %>%
  mutate(week = factor(week, seq(min(week), max(week)))) %>%
  complete(day = weekdays, week) %>%
  mutate(commits = replace(commits, commits > 5, 5)) %>%
  ggplot(aes(x = week, y = factor(day, levels = rev(weekdays)), fill = commits)) +
  geom_tile(color = "white", linewidth = 0.8) +
  guides(fill = guide_colorbar(title = NULL, barwidth = 0.5)) +
  scale_fill_gradientn(colors = colorRampPalette(c("#ADDB7B", "#66A61E"))(10), limits = c(1, 5), na.value = "grey90") +
  labs(title = "Commit activity of past 30 days") +
  theme_portfolio +
  theme(panel.grid = element_blank())
```


```{r, echo = FALSE, fig.width = 10, fig.height = 2.5}
grid::grid.newpage()
print(plot_top_proj, vp = grid::viewport(x = 0.25, y = 0.5, width = 0.5, height = 1))
print(plot_commits_boxes, vp = grid::viewport(x = 0.75, y = 0.5, width = 0.5, height = 1))
```


----------

## References

This portfolio is an R notebook that automatically retrieves citation and profile data from [Google scholar](https://scholar.google.com/) and [Github](https://github.com/). Retrieval is performed using R packages [scholar](https://github.com/jkeirstead/scholar) and [gh](https://github.com/r-lib/gh).
The source code is available on [GitHub](https://github.com/m-jahn/CV/portfolio).

