name: Update README cards

on:
  schedule:
    - cron: "0 6 * * 1"
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - uses: prefix-dev/setup-pixi@v0
        with:
          cache: true

      - name: make portfolio
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pixi run make-portfolio

      - name: commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Add changes" -a || echo "No changes to commit"

      - name: push changes
        uses: ad-m/github-push-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
